<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <Version>1.0.$([System.DateTime]::Now.ToString("yyMMdd")).$([System.DateTime]::Now.ToString("HHmm"))</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.0.1" />
    <PackageReference Include="EPPlus" Version="7.5.2" />
  </ItemGroup>
  
  <ItemGroup>
    <None Update="data\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
