<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <GenerateProgramFile>false</GenerateProgramFile>

    <Version>1.0.$([System.DateTime]::UtcNow.ToString("yy")).$([System.DateTime]::UtcNow.ToString("MMdd"))</Version>
    <AssemblyVersion>1.0.$([System.DateTime]::UtcNow.ToString("yy")).$([System.DateTime]::UtcNow.ToString("MMdd"))</AssemblyVersion>
    <FileVersion>1.0.$([System.DateTime]::UtcNow.ToString("yy")).$([System.DateTime]::UtcNow.ToString("MMdd"))</FileVersion>
    <InformationalVersion>1.0.$([System.DateTime]::UtcNow.ToString("yy")).$([System.DateTime]::UtcNow.ToString("MMdd"))</InformationalVersion>
    
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>

    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.2" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.2" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.2.2" Condition="'$(Configuration)' == 'Debug'" />
    
    <PackageReference Include="CsvHelper" Version="33.0.1" />
    <PackageReference Include="EPPlus" Version="7.5.2" />
    
    <!-- Use xUnit only -->
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="audio\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\AppIcon.png" />
  </ItemGroup>
</Project>
